# Codecov.io configuration
coverage:
  precision: 2
  round: down
  range: "70...100"
  notify:
    require_ci_to_pass: yes
    slack:
      default:
        url: "https://hooks.slack.com/services/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"
        branches: lbmdem              
        threshold: 1%
        attachments: "sunburst, diff" 
        message: "template string"  
  status:
    project: yes
    patch: yes
    changes: yes

  ignore: # files and folders for processing
    - external/*
comment:
  layout: "header, diff, changes"

behavior: default
