#########################
# project configuration #
#########################

# C++ project
language: cpp

dist: trusty
sudo: required


################
# build matrix #
################
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
      env: COMPILER=g++-4.9
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env: COMPILER=g++-5
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
      env: COMPILER=clang++-3.6
    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.7
          packages:
            - clang-3.7
      env: COMPILER=clang++-3.7
  
    - os: linux
      compiler: gcc
      before_install: echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-certificates.crt
      addons:
        apt:
          sources: ['ubuntu-toolchain-r-test']
          packages: ['g++-5', 'valgrind']
        coverity_scan:
          project:
            name: "cb-geo/lbmdem"
            description: "LBM-DEM Coverity scan build submitted via Travis CI"
          notification_email: cued.geomechanics@gmail.com
          build_command_prepend: "make clean ; sudo cp $(which g++-5) $(which g++)"
          build_command: "make"
          branch_pattern: coverity_scan
      env:
        - COMPILER=g++-5
        - SPECIAL=coverity


################
# before script #
################
before_script:
    - aclocal -I ./m4 && autoconf && automake --add-missing

################
# build script #
################

script:
    - ./configure 
    - make clean && make check
    - ./lbmdem
    - ./lbmdemtest

notifications:
  slack:
    rooms:
      - cb-geo:0N3fJy823MGsJvcDB91m4p8H#lbmdem
